# Generated by Django 3.2.6 on 2021-08-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='todo',
        ),
    ]
