# Generated by Django 3.2.6 on 2021-09-06 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectMembers',
        ),
    ]
