# Generated by Django 3.2.6 on 2021-10-06 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_project_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
